version: '3.8'

services:
  corehub:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - DATABASE_URL=postgresql://karl_ai_db_user:ezn3WjgVE1O7VE8OArBo81hjGRcyriKZ@dpg-d3tcmtf5r7bs73en3ed0-a/karl_ai_db
      - CORS_ORIGINS=https://karl-ai-dashboard.railway.app
    depends_on:
      - db
    restart: unless-stopped

  devagent:
    build: .
    command: ["python", "agents/devagent/app/main.py", "loop", "--interval", "300"]
    environment:
      - ENVIRONMENT=production
      - COREHUB_URL=http://corehub:8000
      - DATABASE_URL=postgresql://karl_ai_db_user:ezn3WjgVE1O7VE8OArBo81hjGRcyriKZ@dpg-d3tcmtf5r7bs73en3ed0-a/karl_ai_db
    depends_on:
      - corehub
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=karl_ai_db
      - POSTGRES_USER=karl_ai_db_user
      - POSTGRES_PASSWORD=ezn3WjgVE1O7VE8OArBo81hjGRcyriKZ
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data: