services:
  # CoreHub API - Web Service
  - type: web
    name: karl-ai-corehub
    env: python
    region: oregon
    plan: free
    buildCommand: |
      pip install poetry
      poetry config virtualenvs.create false
      poetry install --no-dev
    startCommand: poetry run uvicorn corehub.api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: karl-ai-db
          property: connectionString
      - key: CORS_ORIGINS
        value: https://karl-ai-dashboard.onrender.com
    healthCheckPath: /health

  # Dashboard Next.js - Web Service  
  - type: web
    name: karl-ai-dashboard
    env: node
    region: oregon
    plan: free
    buildCommand: |
      cd dashboard
      npm install
    startCommand: |
      cd dashboard
      npm run build
      npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://karl-ai-corehub.onrender.com
    healthCheckPath: /

  # DevAgent - Background Worker
  - type: worker
    name: karl-ai-devagent
    env: python
    region: oregon
    plan: free
    buildCommand: |
      pip install poetry
      poetry config virtualenvs.create false
      poetry install --no-dev
    startCommand: poetry run python agents/devagent/app/main.py loop --interval 300
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: COREHUB_URL
        value: https://karl-ai-corehub.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: karl-ai-db
          property: connectionString

# PostgreSQL Database
databases:
  - name: karl-ai-db
    plan: free
    region: oregon
